version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /QIIME2-Ic:-Demultiplexed-data-(single-end).ga
  testParameterFiles:
  - /QIIME2-Ic:-Demultiplexed-data-(single-end)-tests.yml
  authors:
  - name: Debjyoti Ghosh
    orcid: 0009-0008-1496-1677
  - name: "Helmholtz-Zentrum f\xFCr Umweltforschung - UFZ"
    address: "Permoserstra\xDFe 15, 04318 Leipzig"
