version: 1.2
workflows:
- name: PretextMap_Generation
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /PretextMap_Generation.ga
  testParameterFiles:
  - /PretextMap_Generation-tests.yml
  authors:
  - name: Patrik Smeds
    orcid: 0000-0001-6228-2785
  - name: Galaxy
  - name: Delphine Lariviere
    orcid: 0000-0001-6421-3484
- name: Bam-To-Excel-Reads:-13-24
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /Bam-To-Excel-Reads:-13-24.ga
- name: PretextMap-Generation-from-2-haplotypes
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /PretextMap-Generation-from-2-haplotypes.ga
  authors:
  - name: Patrik Smeds
    orcid: 0000-0001-6228-2785
  - name: Galaxy
  - name: Delphine Lariviere
    orcid: 0000-0001-6421-3484
