version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /Standard-scRNA-seq-with-Scanpy.ga
  testParameterFiles:
  - /Standard-scRNA-seq-with-Scanpy-tests.yml
  authors:
  - name: Pavankumar Videm
    orcid: 0000-0002-5192-126X
  - name: Hans-Rudolf Hotz
    orcid: 0000-0002-2799-424X
  - name: Mehmet Tekman
    orcid: 0000-0002-4181-2676
  - name: "Bérénice Batut"
    orcid: 0000-0001-9852-1987