version: 0.1
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /MAGs-generation.ga
  testParameterFiles:
  - /MAGs-generation-tests.yml
  authors:
  - name: Paul Zierep
    orcid: 0000-0003-2982-388X
  - name: "Bérénice Batut"
    orcid: 0000-0001-9852-1987
  - name: Mina Hojat Ansari
    orcid: 0000-0002-3602-7884
  - name: "Patrick Bühler"
    orcid: 0000-0003-2982-388X
  - name: Santino Faack
    orcid: 0000-0003-2982-388X
