version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /encyclopedia.ga
  testParameterFiles:
  - /encyclopedia-tests.yml
  authors:
  - name: GalaxyP
    url: https://galaxyp.org/
